SET DEFINE OFF;
Insert into DZ_SWAGGER3_PARENT_SERVER_MAP
   (PARENT_ID, SERVER_ID, SERVER_ORDER, VERSIONID)
 Values
   ('SAMPLE', 'sample1', 20, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_SERVER_MAP
   (PARENT_ID, SERVER_ID, SERVER_ORDER, VERSIONID)
 Values
   ('SAMPLE', 'sample2', 30, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_SERVER_MAP
   (PARENT_ID, SERVER_ID, SERVER_ORDER, VERSIONID)
 Values
   ('SAMPLE', 'sampleWATERS', 10, 'SAMPLE');
COMMIT;
