SET DEFINE OFF;
Insert into DZ_SWAGGER3_VERS
   (VERSIONID, IS_DEFAULT, VERSION_OWNER, VERSION_CREATED, VERSION_NOTES)
 Values
   ('SAMPLE', 'FALSE', 'PDZIEMIE', TO_DATE('5/25/2019', 'MM/DD/YYYY'), 'Sample Set');
COMMIT;
