SET DEFINE OFF;
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.pNavigationType', 10, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.pComID', 20, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.pPermanentIdentifier', 30, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.pReachCode', 40, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.pStartHydroSequence', 50, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.pStartMeasure', 60, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.pStopComID', 70, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.pStopPermanentIdentifier', 80, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.pStopReachCode', 90, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.pStopHydroSequence', 100, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.pStopMeasure', 110, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.pMaxDistanceKm', 120, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.pMaxFlowTimeDay', 130, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.Navigation30.GET', 'Sample.f', 140, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.pNavigationType', 10, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.pComID', 20, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.pPermanentIdentifier', 30, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.pReachCode', 40, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.pStartHydroSequence', 50, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.pStartMeasure', 60, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.pStopComID', 70, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.pStopPermanentIdentifier', 80, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.pStopReachCode', 90, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.pStopHydroSequence', 100, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.pStopMeasure', 110, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.pMaxDistanceKm', 120, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.pMaxFlowTimeDay', 130, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Navigation30.POST', 'Sample.f', 140, 'FALSE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Streamcat.POST', 'Sample.pComID', 10, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Streamcat.POST', 'Sample.pFeatureID', 20, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Streamcat.POST', 'Sample.pPermanentIdentifier', 30, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Streamcat.POST', 'Sample.pAreaOfInterest', 40, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Streamcat.POST', 'Sample.pReachCode', 50, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Streamcat.POST', 'Sample.pMeasure', 60, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Streamcat.POST', 'Sample.pLandscapeMetricType', 70, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Streamcat.POST', 'Sample.pLandscapeMetricClass', 80, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Streamcat.POST', 'Sample.pReturnGeometry', 90, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Streamcat.POST', 'Sample.pFilenameOverride', 100, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.Streamcat.POST', 'Sample.f', 110, 'FALSE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.randomnav.CALLBACK.POST', 'Sample.CallbackID', 10, 'FALSE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, REQUESTBODY_FLAG, VERSIONID)
 Values
   ('Sample.randomnav.CALLBACK.POST', 'Sample.CallbackThing', 20, 'TRUE', 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.randomnav.GET', 'Sample.pRegion', 10, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.randomnav.GET', 'Sample.f', 20, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_PARM_MAP
   (PARENT_ID, PARAMETER_ID, PARAMETER_ORDER, VERSIONID)
 Values
   ('Sample.randomnav.GET', 'Sample.api_key', 30, 'SAMPLE');
COMMIT;
