SET DEFINE OFF;
Insert into DZ_SWAGGER3_PARENT_SECSCHM_MAP
   (PARENT_ID, SECURITYSCHEME_ID, SECURITYSCHEME_NAME, SECURITYSCHEME_ORDER, VERSIONID)
 Values
   ('SAMPLE', 'SAMPLE.SEC.1', 'sample.security.apikey', 10, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_SECSCHM_MAP
   (PARENT_ID, SECURITYSCHEME_ID, SECURITYSCHEME_NAME, SECURITYSCHEME_ORDER, VERSIONID)
 Values
   ('SAMPLE', 'SAMPLE.SEC.2', 'sample.security.http', 20, 'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_SECSCHM_MAP
   (PARENT_ID, SECURITYSCHEME_ID, SECURITYSCHEME_NAME, OAUTH_FLOW_SCOPES, SECURITYSCHEME_ORDER, 
    VERSIONID)
 Values
   ('SAMPLE', 'SAMPLE.SEC.3', 'sample.security.oauth2', 'poweruser,admin', 30, 
    'SAMPLE');
Insert into DZ_SWAGGER3_PARENT_SECSCHM_MAP
   (PARENT_ID, SECURITYSCHEME_ID, SECURITYSCHEME_NAME, SECURITYSCHEME_ORDER, VERSIONID)
 Values
   ('SAMPLE', 'SAMPLE.SEC.4', 'sample.security.openIdConnect', 40, 'SAMPLE');
COMMIT;
